Improved code, added some tests
anthoskountouris/guessWhoScala pull request #2
Opened 2024-04-09 13:55 UTC by anthoskountouris

2024-04-12 11:07 UTC, GauravJai requested changes
### Suggestion for using small loose components:
instead of writing a game for two players can be just one player for it, and can break the whole code in small components, that could be as below 

* Data Preparation: 
	* a component for preparing the list of characters that could be reused for test class as well. i.e. case class
* Select a random character at the start of game:
	* Write a function to randomly select a character to represent the start of the game.​
* Input/Output Handling:
	* Methods for user input and printing characters. 
* Game Logic:
	* A Methods for picking random characters and questions, removing characters, and determining game outcomes.
* Unit Tests:
	* Separate unit tests for each function to ensure correctness.
* Error Handling:
	* Handling invalid user inputs and other potential errors gracefully.

2024-04-12 11:07 UTC, GauravJai commented on src/main/scala/Character.scala
>  }
Brackets are not required with case classes, those can be removed.

2024-04-12 11:07 UTC, GauravJai commented on src/main/scala/Main.scala
> +    var listOfCharacters:List[Character] = List(character1,
```suggestion
    // Consider using more descriptive variable names and avoid duplication of code wherever possible
    val characters: List[Character] = List(
     Character("Tom", true, true, true, false),
     Character("John", true, true, false, true),
     Character("Anthos", true, false, true, true),
     Character("Kokos", true, true, true, true),
     Character("Will", true, false, false, false),
     Character("April", false, true, true, false),
     Character("Maria", false, true, false, true),
     Character("Andrea", false, true, false, false),
     Character("Connie", false, true, true, true)
  )
```

2024-04-12 11:07 UTC, GauravJai commented on src/main/scala/Main.scala
>    val trueOrFalse:Boolean = if (yesOrNo=="yes"){
// Simplify condition
```suggestion
  val trueOrFalse: Boolean = yesOrNo == "yes"
```

2024-04-15 10:07 UTC, anthoskountouris commented
I removed duplicate code, changed it from two player to just one, created a function that generates the desired data to play the game, created a function which asks user for a valid input, and put the main logic in a function which uses recursion instead of a while loop.

2024-04-16 11:44 UTC, GauravJai approved these changes

2024-04-16 14:52 UTC, merged